services:
- type: web
  name: linebot-flask-sander
  env: python
  repo: https://github.com/helgesander02/linebot_flask.git
  plan: free
  autoDeploy: false
  buildCommand: pip install gunicorn -r requirements.txt
  startCommand: gunicorn hellofly:app
  envVars:
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false
