services:
- type: web
  name: linebot-flask-sander
  env: python
  repo: https://github.com/helgesander02/den_no_suke_LineBot.git
  plan: free
  autoDeploy: false
  buildCommand: pip install gunicorn -r requirements.txt
  startCommand: gunicorn hellofly:app
  envVars:
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false
  - key: User-Agent
    sync: false
  - key: Internal_Database_URL
    sync: false
